# Generated by Django 5.1.1 on 2024-09-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_groups_customuser_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.IntegerField(null=True),
        ),
    ]
